on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test current repo
        uses: ./ # Uses an action in the root directory
        id: testcurrent
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print current repo
        run: |
          echo release: ${{ steps.testcurrent.outputs.release }}
          echo ""
          echo releaseAssets: ${{ steps.testcurrent.outputs.releaseAssets }}

      - name: Test given repo
        uses: ./ # Uses an action in the root directory
        id: testgiven
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: kagekirin/github-get-latest-release-action
      - name: Print given repo
        run: |
          echo release: ${{ steps.testgiven.outputs.release }}
          echo ""
          echo releaseAssets: ${{ steps.testgiven.outputs.releaseAssets }}

      - name: Test owner repo
        uses: ./ # Uses an action in the root directory
        id: testowner
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: kagekirin
          repo: github-get-latest-release-action
          excludes: draft
      - name: Print owner repo
        run: |
          echo release: ${{ steps.testowner.outputs.release }}
          echo ""
          echo releaseAssets: ${{ steps.testowner.outputs.releaseAssets }}

      - name: Test other repo
        uses: ./ # Uses an action in the root directory
        id: testother
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: kagekirin/metagen-rs
      - name: Print other repo
        run: |
          echo release: ${{ steps.testother.outputs.release }}
          echo ""
          echo releaseAssets: ${{ steps.testother.outputs.releaseAssets }}
          echo releaseAssets: ${{ steps.testother.outputs.releaseAssets[0].browser_download_url }}
